config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    root to: "users#index"
  end

  devise_for :users
  root to: 'campaigns#index'

  resources :campaigns do
    resources :comments
    resources :todos do
      resources :comments
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  has_many :todos
  has_many :comments

  validates :title, presence: true
  validates :tags, presence: true
  validates :estimated_duration, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :campaign, optional: true
  belongs_to :todo, optional: true

  validates :title, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :campaign
  belongs_to :user
  has_many :comments

  validates :items, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :set_default_expertise
  has_many :campaigns
  has_many :todos
  has_many :comments
  # or
  # before_validation :set_default_role

  private
  def set_default_expertise
    self.expertise ||= :novice
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin


    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_user && current_user.expertise == "expert"
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: :campaigns
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :status, :expertise, :profession, :service]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end


end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = policy_scope(Campaign)
  end

  def show
    @campaign = Campaign.find(params[:id])
    authorize @campaign
  end

  def new
    @campaign = Campaign.new
    @user = current_user
    authorize @campaign
  end

  def create
    @campaign = Campaign.new(params_campaign)
    @user = current_user
    @campaign.user = @user
    authorize @campaign
    if @campaign.save
      redirect_to campaign_path(@campaign), notice: "Campaign Added to System"
    else
      render :new
    end
  end
  private

  def params_campaign
    params.require(:campaign).permit(:title, :tags, :estimated_duration, :user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = policy_scope(Comment)
  end

  def new
    @comment = Comment.new
    @user = current_user
    authorize @comment
  end

  def create
    if params[:todo_id]
      @parent = Todo.find(params[:todo_id])
    elsif params[:campaign_id]
      @parent = Campaign.find(params[:campaign_id])
    end

    @comment = @parent.comments.build(params_comment)
    @comment.user = current_user
    authorize @comment
    if @comment.save
      if @parent.is_a?(Todo) # template error with this included: (== params[:post_id])
        flash[:notice] = 'Comment saved successfully'
        redirect_to [@parent.campaign]
      elsif @parent.is_a?(Campaign)
        flash[:notice] = 'Comment saved successfully'
        redirect_to @parent
       end
    end
  end

  private

  def params_comment
    params.require(:comment).permit(:title, :user_id)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = policy_scope(Todo)
  end

  def new
    @todo = Todo.new
    @campaign = Campaign.find(params[:campaign_id])
    @user = current_user
    authorize @todo
  end

  def create
    @todo = Todo.new(params_todo)
    @campaign = Campaign.find(params[:campaign_id])
    @todo.campaign = @campaign
    @user = current_user
    @todo.user = @user
    authorize @todo
    if @todo.save
      redirect_to campaign_path(@campaign), notice: "Todo List Posted"
    else
      render :new
    end
  end

  private

  def params_todo
    params.require(:todo).permit(:items, :campaign_id, :user_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campaigns/edit.html.erb
<h2>Edit Your Campaign!</h2>
<%= simple_form_for @campaign do |c| %>
  <%= c.input :title, label: "Title" %>
  <%= c.input :tags, label: "Tags", placeholder: "Put tags in here separated by commas" %>
  <%= c.input :estimated_duration, label: "How many months is the anticipated campaign?" %>
  <%= c.button :submit, class:"btn-add" %>
<% end %>

app/views/campaigns/index.html.erb
<%= render 'shared/banner' %>
<div class="row">
  <% @campaigns.each do |campaign| %>
  <div class="col-xs-12 col-sm-4">
    <%= link_to campaign_path(campaign) do %>
      <div class="card">
        <div class="card-contents">
          <h3><%= campaign.title %></h3>
          <hr width="70%">
          <h5 class="tags"><%= campaign.tags %></h5>
          <p>Length: <%= campaign.estimated_duration.to_s + " Months" %></p>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>


<div class="new-campaign-banner">
  <% if policy(Campaign).new? %>
    <p><%= link_to "You are an Expert! Create a New Campaign", new_campaign_path %></p>
  <% end %>
</div>

app/views/campaigns/new.html.erb
<h2>Make A New Campaign!</h2>
<%= simple_form_for @campaign do |c| %>
  <%= c.input :title, label: "Title" %>
  <%= c.input :tags, label: "Tags", placeholder: "Put tags in here separated by commas" %>
  <%= c.input :estimated_duration, label: "How many months is the anticipated campaign?" %>
  <%= c.button :submit, class:"btn-add" %>
<% end %>

app/views/campaigns/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://source.unsplash.com/random/1500x300');">
  <div class="banner-content">
    <h1><%= @campaign.title %></h1>
    <p class="tags"><%= @campaign.tags %></p>
    <p>Length: <%= @campaign.estimated_duration.to_s + " Months" %></p>
  </div>
</div>
<div class="comments-banner">
  <p><%= link_to "Add a Comment", new_campaign_comment_path(@campaign) %></p>
  <% @campaign.comments.each do |c| %>
    <p><%= c.title %></p>
    <h6 style="font-size: 10px">Created by:<%= c.user.username %> at <%= c.created_at %></h6>
  <% end %>
</div>
<div class="todo-banner">
<p>To Do Lists</p>
  <div class="row">
<% @campaign.todos.each do |t| %>
    <div class="col-xs-12 col-sm-4">
  <div class="todo-card todo-card-corner">
    <p><%= t.items %></p>
    <% if t.user.expertise.include? "novice" %>
    <p><%= link_to "Add a Comment", new_campaign_todo_comment_path(@campaign, t) %></p>
    <% end %>
    <% t.comments.each do |c| %>
      <p><%= c.title %></p>
    </div>
    <% end %>
  </div>
  </div>
<% end %>

</div>
<p><%= link_to "Add a Todo List", new_campaign_todo_path(@campaign) %></p>

app/views/comments/new.html.erb
<h2>Comment</h2>
<% if params[:todo_id] %>
  <%= simple_form_for [@parent, @comment], url: campaign_todo_comments_path do |c| %>
    <%= c.input :title, label: "Put Your Comment Here" %>
    <%= c.button :submit, class:"btn-add" %>
  <% end %>
<% elsif params[:campaign_id] %>
  <%= simple_form_for [@parent, @comment], url: campaign_comments_path do |c| %>
    <%= c.input :title, label: "Put Your Comment Here" %>
    <%= c.button :submit, class:"btn-add" %>
  <% end %>
<% end %>

app/views/fields/select_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.select(field.attribute, field.choices) %>
</div>

app/views/fields/select_field/_index.html.erb
<%= field.to_s %>

app/views/fields/select_field/_show.html.erb
<%= field.to_s %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Campaignion</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link rel="shortcut icon" type="image/png" href="http://res.cloudinary.com/dofuzeof4/image/upload/v1526485823/icon-campaignon-01_aqvipj.png"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://res.cloudinary.com/dofuzeof4/image/upload/v1526486309/download_oodgwb.jpg');">
  <div class="banner-content">
    <h1>Your Companion for the Most Important Campaigns</h1>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://res.cloudinary.com/dofuzeof4/image/upload/v1526485823/icon-campaignon-01_aqvipj.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<h2>Make A Todo List!</h2>
<%= simple_form_for @todo, url: campaign_todos_path do |t| %>
  <%= t.input :items, label: "Todo List Items" %>
  <%= t.button :submit, class:"btn-add" %>
<% end %>